/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import modelo.JugadorRuleta;
import modelo.Numero;

/**
 *
 * @author Euge
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero(ArrayList<Numero> numeros, ActionListener al) {
        initComponents();
        mostrarTablero(numeros,al);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void mostrarTablero(ArrayList<Numero> numeros, ActionListener al) {
        GridLayout disenio = new GridLayout(3, numeros.size());
        setLayout(disenio);
        
        for(Numero n:numeros){
            BotonRuleta b = new BotonRuleta(n.getValor() + "");
            b.setBackground(n.getColor());
            b.setForeground(Color.white);
            b.addActionListener(al);
            b.setNumero(n);
            JugadorRuleta j = n.getJugador();
            if(j==null) b.setToolTipText("Sin marcar");
            else b.setToolTipText(j.getJugador().getNombreCompleto());
            add(b);
        }
    }
}
