/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Euge
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalizar = new javax.swing.JButton();
        ingresoCasino1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INGRESO AL CASINO");
        getContentPane().setLayout(null);

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(finalizar);
        finalizar.setBounds(110, 170, 170, 50);

        ingresoCasino1.setText("Ingresar al Casino");
        ingresoCasino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoCasino1ActionPerformed(evt);
            }
        });
        getContentPane().add(ingresoCasino1);
        ingresoCasino1.setBounds(110, 70, 170, 50);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoCasino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoCasino1ActionPerformed
        // TODO add your handling code here:
        ingresar();
    }//GEN-LAST:event_ingresoCasino1ActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
        finalizar();
    }//GEN-LAST:event_finalizarActionPerformed

    private void ingresar(){
        new VistaLoginV1(this,false).setVisible(true);
    }
    
    private void finalizar() {
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finalizar;
    private javax.swing.JButton ingresoCasino1;
    // End of variables declaration//GEN-END:variables
}
