/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMesa;
import controlador.VistaMesa;
import java.util.ArrayList;
import javax.swing.JSplitPane;
import modelo.Jugador;
import modelo.JugadorRuleta;
import modelo.Mesa;
import modelo.Numero;

/**
 *
 * @author Euge
 */
public class VistaMesaV1 extends javax.swing.JDialog implements VistaMesa{
    
    private ControladorMesa controlador;
    private JSplitPane split = new JSplitPane();

    public VistaMesaV1(Mesa m, Jugador j) {
        initComponents();
        JugadorRuleta jr= m.buscarJugador(j);
        controlador = new ControladorMesa(this,m,jr);
        lbl.setText("Mesa " + m.getNombre());
        controlador.cargarJugadoresActivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl.setText("jLabel1");
        getContentPane().add(lbl);
        lbl.setBounds(114, 38, 178, 14);

        jScrollPane1.setViewportView(listaJugadores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 40, 130, 130);

        jLabel1.setText("Jugadores en Mesa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 20, 100, 14);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JList listaJugadores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrar(ArrayList<Numero> numeros) {

    }

    @Override
    public void mostrarJugadores(ArrayList<Jugador> j) {
        ArrayList<String> listado = new ArrayList<>();
        for (Jugador ju : j){
            listado.add(ju.getNombreCompleto());
        }
        listaJugadores.setListData(listado.toArray());
    }


}
